### ISSUE TITLE
Corrigir página do histórico

### ISSUE THREAD

**Issue by ritzare** [fga-eps-mds/2021-2-Oraculo-Doc#23]
- [x] Corrigir bug

**Comment by Arthurlima544** [comment]
Página do histórico de registros está toda em branco.

**Comment by Arthurlima544** [comment]
## Descrição do bug:
Ao selecionar o botão "histórico de alteração" é mostrado uma tela em branco. Na tela de visualização do registro não deve haver ser mostrado o histórico.
